services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      - 784:784/udp
      - 853:853/tcp
      - 8080:8080/tcp
      - 8443:8443/tcp
    volumes:
      - /home/moon/docker/AdGuardHome/work:/opt/adguardhome/work
      - /home/moon/docker/AdGuardHome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    healthcheck:
      test: nslookup www.google.com || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
      retries: 1
networks:
  default:
    name: adguard
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.5.0/24
