services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - target: "8443"
        host_ip: 127.0.0.1
        published: "8443"
        protocol: tcp
    volumes:
      - /home/moon/docker/AdGuardHome/work:/opt/adguardhome/work    
      - /home/moon/docker/AdGuardHome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: wget --no-verbose --tries=1 --spider https://adb-home.xaoimoon.fr/ || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
      retries: 1
